<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="12" time="0.151" timestamp="2025-07-15T11:50:12.130860+09:00" hostname="surface-shiori"><testcase classname="tests.test_book" name="test_lend_and_return" time="0.001" /><testcase classname="tests.test_data_file" name="test_json_files_exist" time="0.001" /><testcase classname="tests.test_data_file" name="test_no_duplicates_in_merged_file[get_book_json_files-keys_to_check0-book]" time="0.001" /><testcase classname="tests.test_data_file" name="test_no_duplicates_in_merged_file[get_user_json_files-keys_to_check1-user]" time="0.001" /><testcase classname="tests.test_library" name="test_register_book_and_user" time="0.001" /><testcase classname="tests.test_loader_factory" name="test_book_load_entities" time="0.016" /><testcase classname="tests.test_loader_factory" name="test_user_load_entities" time="0.005" /><testcase classname="tests.test_loader_factory" name="test_make_book_and_register" time="0.001" /><testcase classname="tests.test_loader_factory" name="test_make_user_and_register" time="0.001" /><testcase classname="tests.test_presenter" name="test_transform_info" time="0.000" /><testcase classname="tests.test_presenter" name="test_show_info_stdout" time="0.001" /><testcase classname="tests.test_user" name="test_borrow_and_return_history" time="0.000"><failure message="ValueError: ISBN isbn1 の本はすでに借りています。">def test_borrow_and_return_history() -&gt; None:
        user = User("u1", "山田 太郎", history=[])
    
        user.borrow_book("isbn1")
        assert "isbn1" in user.borrowed_books
        assert user.history[-1] == "借用: isbn1"
    
        # 二重登録されない
&gt;       user.borrow_book("isbn1")

tests\test_user.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;core.domain.user.User object at 0x00000258B8D3A810&gt;, isbn = 'isbn1'

    def borrow_book(self, isbn: str) -&gt; None:
        if isbn in self.borrowed_books:
&gt;           raise ValueError(f"ISBN {isbn} の本はすでに借りています。")
E           ValueError: ISBN isbn1 の本はすでに借りています。

core\domain\user.py:15: ValueError</failure></testcase></testsuite></testsuites>